# Generated by Django 5.2.1 on 2025-05-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User1',
        ),
    ]
